const newsListActionTypes = {
    NEWS_FETCH_REQUESTED: 'NEWS_FETCH_REQUESTED',
    NEWS_FETCH_SUCCESS: 'NEWS_FETCH_SUCCESS',
    NEWS_FETCH_FAIL:'NEWS_FETCH_FAIL',
    NEWS_FETCH_MORE_REQUESTED: 'NEWS_FETCH_MORE_REQUESTED',
    UP_VOTE_POST: 'UP_VOTE_POST',
    FILTERED_NEWS: 'FILTERED_NEWS',
    FILTERED_NEWS_SUCCESS: 'FILTERED_NEWS_SUCCESS',
};

export default newsListActionTypes;